Deposit table
Agave-DAO/agave-frontend pull request #26
Opened 2021-06-07 21:33 UTC by famole

Added Sundeep changes.
Fixed table style and created deposit default screen.

2021-06-08 03:42 UTC, zedkai requested changes
Please change this to no longer use `IMarketDataTable`, the constant `marketData`, or the `BasicTable`.

Instead, please retrieve market data in the same manner as [/src/views/Markets/index.tsx](https://github.com/Agave-DAO/agave-frontend/blob/8d0be47e632abdecb1cf710fc88be96d321684e3/src/views/Markets/index.tsx#L209-L220) and use `SortedHtmlTable` as is done [in that same file](https://github.com/Agave-DAO/agave-frontend/blob/8d0be47e632abdecb1cf710fc88be96d321684e3/src/views/Markets/index.tsx#L308).

2021-06-10 02:31 UTC, famole commented
Fixed data source issue.
Added header props and sort icon to the _sortedHtmlTable_
Switch component updated, styled components implementation was removed.

<img width="1274" alt="Screen Shot 2021-06-09 at 11 27 30 PM" src="https://user-images.githubusercontent.com/1489405/121455429-d617a900-c97a-11eb-9d3c-30d1e4ba7919.png">

2021-06-12 03:32 UTC, zedkai requested changes
Currently broken; this code would crash if the user selects the page and flips away from it again while on a slow network connection.

2021-06-12 03:32 UTC, zedkai commented on src/views/Deposit/layout.tsx
> +              {/* <Search
Added this to a [work-item](https://trello.com/c/20XYvRSR/27-search-functionality-on-deposit-withdrawal-etc-pages-currently-disabled) for later.

2021-06-12 03:32 UTC, zedkai commented on src/hooks/balance.ts
> +export const useTokenBalance = (tokenAddress: string): Promise<BigNumber> | undefined => {
No, not at all; Use the hooks for this, namely `useUserAssetBalance` which returns an object containing field `data`; when `data` is non-`undefined`, it contains the balance for that user.

2021-06-12 03:32 UTC, zedkai commented on src/views/Deposit/DepositTable.tsx
> +    useTokenBalance(tokenAddress)?.then((value: BigNumber) => {
Invoking a hook like this is incorrect and should have resulted in React full-on crashing- I'm surprised it didn't.

2021-06-12 03:32 UTC, zedkai commented on src/views/Deposit/DepositTable.tsx
> +      setBalance(result)
Invoke `useUserAssetBalance` the same way you did with `useAssetPriceInDai` and you would be able to avoid using state at all. Calling `set(State)` from an async callback like this is illegal in React as it can be fulfilled after the component is unmounted, which would trigger a render with no component.

2021-06-12 22:28 UTC, zedkai requested changes

2021-06-12 22:28 UTC, zedkai commented on src/views/Deposit/DepositTable.tsx
> +import { FixedFromRay } from "../../utils/fixedPoint";
Doesn't look like you use this at all?

2021-06-12 22:28 UTC, zedkai commented on src/views/Deposit/DepositTable.tsx
> +    const balance = useUserAssetBalance(tokenAddress)
Semicolons. Use the `prettier` to format.

2021-06-12 22:28 UTC, zedkai commented on src/views/Deposit/DepositTable.tsx
> +    console.log(Number(price.data))
Leftover debug log?

2021-06-12 22:28 UTC, zedkai commented on src/views/Deposit/DepositTable.tsx
> +    const renderBalanceDai = balanceNumber ? (Number(price.data) * balanceNumber).toFixed(2) : "-"
These look super sketchy, but- since they're only for display- I'll check them for accuracy myself later.

2021-06-12 22:28 UTC, zedkai commented on src/views/Deposit/DepositTable.tsx
> +              $ {renderBalanceDai ?? "-"}
`balance` was originally the balance in tokens, not in Dai. `balanceUsd` would be where the balance in Dai should be placed.

2021-06-12 22:34 UTC, famole commented on src/views/Deposit/DepositTable.tsx
> +import { FixedFromRay } from "../../utils/fixedPoint";
Removed all unused imports

2021-06-12 22:39 UTC, famole commented on src/views/Deposit/DepositTable.tsx
> +              $ {renderBalanceDai ?? "-"}
The token balance needs to be on top by design, and the amount in USD under it. Just updated variable naming to make it clear.

2021-06-12 22:45 UTC, zedkai approved these changes
That's better. Merging.

2021-06-12 22:46 UTC, merged