Active deposits table
Agave-DAO/agave-frontend pull request #28
Opened 2021-06-15 15:33 UTC by famole

Added header text
Added active deposits table getting real data

2021-06-15 22:31 UTC, zedkai requested changes

2021-06-15 22:31 UTC, zedkai commented on src/views/Deposit/DepositMyDepositsTable.tsx
> +  }, [assets]);
```suggestion
  const total = React.useMemo(() => {
    return assets.reduce((memo, next) => memo + (ethers.utils.formatEther(next.balance) ?? 0), 0);
  }, [assets]);
  return React.useMemo(() => {
    return (
      <Flex w="100%" flexDir="column" >
        {assets.map((value, i) =>
          (
          <Box key={i}>
            <BalanceView asset={value} />
            <Box h="0.1rem" backgroundColor="primary.50" />
          </Box>
          )
        )}  
        <Flex
          alignSelf="center"
          justifyContent="space-between"
          w="100%"
          px={{ base: "2.4rem", md: "2.4rem" }} pt={6}
        >
          <Text>
            Total
          </Text>
          <Text fontWeight="bold">
            $ {total}
          </Text>
        </Flex>
      </Flex>
    )
  }, [assets, total]);

```

2021-06-15 22:31 UTC, zedkai commented on src/views/Deposit/DepositMyDepositsTable.tsx
> +  }, [assets]);
Split responsibilities among `useMemo`s to avoid use of mutations and conflict of multiple concerns. Your prior version didn't actually `return` the `(<Box>...</Box>)` section under the .map, after you started mutating `total`, leading to failing to render entirely.

2021-06-15 22:31 UTC, zedkai commented on src/views/Deposit/DepositMyDepositsTable.tsx
> +return (
Indentation. Please run the formatter before submitting code for review.

2021-06-15 22:31 UTC, zedkai commented on src/views/Deposit/index.tsx
> +  balance: BigNumber
Formatting again, interface member lines should end in semicolons.

2021-06-15 22:31 UTC, zedkai commented on src/views/Deposit/index.tsx
> +  console.log(b)
Leftover debug log, and lack of semicolons.

2021-06-15 22:31 UTC, zedkai commented on src/views/Deposit/index.tsx
> +  const b = useUserDepositAssetBalancesDaiWei()
Looks like you never actually use this `b` variable?

2021-06-16 18:51 UTC, famole commented on src/views/Deposit/DepositMyDepositsTable.tsx
> +  }, [assets]);
Cool, I'll start splitting responsibilities from now on.

2021-06-16 19:30 UTC, zedkai approved these changes

2021-06-16 19:30 UTC, merged