Dashboard v1
Agave-DAO/agave-frontend pull request #29
Opened 2021-06-25 14:05 UTC by famole

Dashboard UI, doesn't include data fetching.

2021-06-27 05:36 UTC, zedkai requested changes
Some performance issues and stylistic inconsistencies, but on the right track.

It looks like parameters aren't being fed their data yet, but you declare that data fetching will be done next, so I'll hold off on drawing a line there just yet.

2021-06-27 05:36 UTC, zedkai commented on src/components/Header/index.tsx
> +          MY DASHBOARD
```suggestion
          DASHBOARD
```

2021-06-27 05:36 UTC, zedkai commented on src/components/Search/index.tsx
> +export default Search;
Please avoid default exports for components; change it to an `export const Search`.
```suggestion
export const Search: React.FC<InputGroupProps> = ({ placeholder, ...props }) => {
  return (
    <InputGroup {...props}>
      <Input
        h={props.h}
        placeholder={placeholder}
        focusBorderColor="primary.100"
      />
      <InputRightElement h="100%" mr={1} children={<SearchIcon />} />
    </InputGroup>
  );
};
```

2021-06-27 05:36 UTC, zedkai commented on src/views/Dashboard/DasboardEmptyState.tsx
> +export const DashboardEmptyState: React.FC<{
Looks like you do a lot of switching on `Deposit` / `Borrow`- would it be easier to just use the parameter to determine content for string interpolations?

2021-06-27 05:36 UTC, zedkai commented on src/views/Dashboard/DashboardTable.tsx
> +  Borrow = "BORR",
There's no reason to abbreviate these; string operations won't change anything significantly when compared to JS overhead.
```suggestion
  Deposit = "Deposit",
  Borrow = "Borrow",
```

2021-06-27 05:36 UTC, zedkai commented on src/views/Dashboard/DashboardTable.tsx
> +  };
These "view" components should not be created in the scope of the parent component, as they have no dependencies upon it, and you're effectively declaring a new component type per render. They are constants and they can be at the top level, otherwise you're reallocating them constantly. Look at how I adjusted it the last time you did this [in DepositTable](https://github.com/Agave-DAO/agave-frontend/blob/4f709a50f826daac8c6c1c039371a3c4aa29b9bf/src/views/Deposit/DepositTable.tsx#L18-L92) and how I originally did it [in Markets](https://github.com/Agave-DAO/agave-frontend/blob/67a7d38c021e5e013c7a37812a7c18a7a5158e69/src/views/Markets/index.tsx#L67-L199).

In the future, Please review changes made to areas you contributed before further building atop the patterns you used, to avoid redundant work like this.

Additionally, consider turning these reused components into something you can import from a central location, instead of copying and pasting them a third or fourth time.

2021-06-27 05:36 UTC, zedkai commented on src/views/Dashboard/DashboardTable.tsx
> +  const columns: Column<AssetRecord>[] = [
Memoize the column declarations the way it's done in [Deposit](https://github.com/Agave-DAO/agave-frontend/blob/4f709a50f826daac8c6c1c039371a3c4aa29b9bf/src/views/Deposit/DepositTable.tsx#L92).

2021-06-27 05:36 UTC, zedkai commented on src/views/Dashboard/index.tsx
> +function Dashboard() {
FCs are preferred, and top-level type definitions are required. Also, prefer non-`default` exports.
```suggestion
export const Dashboard: React.FC<{}> = (_props) => {
```

2021-06-27 05:36 UTC, zedkai commented on src/views/Dashboard/layout.tsx
> +        Aproximate Balance
```suggestion
        Approximate Balance
```

2021-06-27 05:36 UTC, zedkai commented on src/views/Dashboard/layout.tsx
> +};
Don't abbreviate- use descriptive names. Also, pick either objects or enums and stick with it for consistency.

2021-06-27 05:36 UTC, zedkai commented on src/views/Dashboard/layout.tsx
> +export const ModalHFactor: React.FC<{
It doesn't look like this needed exported?

2021-06-27 05:36 UTC, zedkai commented on src/views/Dashboard/layout.tsx
> +                }}
`React.useCallback` to avoid creating a new callback with each render.

Same with the other callbacks in this component.

2021-06-27 05:36 UTC, zedkai commented on src/views/Dashboard/layout.tsx
> +              {mtype === MODAL_TYPES.HF && <ModalHFactor />}
These both have quite a few parameters that you just ... Aren't passing?

2021-07-04 04:25 UTC, famole commented on src/views/Dashboard/layout.tsx
> +              {mtype === MODAL_TYPES.HF && <ModalHFactor />}
Will add this parameters tomorrow, I need to check how to get this data

2021-07-04 06:20 UTC, zedkai commented on src/views/Dashboard/DashboardTable.tsx
> +  const columns: Column<AssetData>[] = [
This still needs `React.useMemo`.

2021-07-04 06:23 UTC, zedkai commented on src/views/Dashboard/layout.tsx
> +              {mtype === MODAL_TYPES.HF && <ModalHFactor />}
Let's do that as a subsequent PR.

2021-07-04 06:38 UTC, zedkai commented on src/views/Dashboard/DashboardTable.tsx
> +const DepositAPYView: React.FC<{ tokenAddress: string }> = ({
Can you move the views from Deposit that match these into a file in `common` and export them, then use the same ones for both files?

2021-07-04 06:39 UTC, zedkai requested changes
A few changes left- see my unresolved comments.

2021-07-04 20:44 UTC, famole commented on src/views/Dashboard/DashboardTable.tsx
> +const DepositAPYView: React.FC<{ tokenAddress: string }> = ({
I exported most of the components to common folder, some of them have different view, in case you see that are still in the screen, this is the why.

2021-07-04 22:05 UTC, zedkai approved these changes
Approved for merge. Please add the parameters to the modals in a second PR.

2021-07-04 22:06 UTC, merged