Fixed empty state dashboard issues
Agave-DAO/agave-frontend pull request #31
Opened 2021-07-05 21:22 UTC by famole

Empty state margin issues and missing text, still working in components reorder usign Flex.
Will be sent in a different PR

2021-07-05 23:59 UTC, zedkai requested changes

2021-07-05 23:59 UTC, zedkai commented on src/views/Dashboard/emptyState.tsx
> +  }, [type]);
This is short enough - and, unlike objects and arrays, both types are primitives and are reference-equal; as a result, `React.useMemo` is unnecessary here, but it doesn't really hurt either. Feel free to leave it, but do try to note why it's unnecessary, and thus why a simple `const` would work.

2021-07-05 23:59 UTC, zedkai commented on src/views/Dashboard/emptyState.tsx
> +      </Text>
Don't undo my changes ^^;
(See beccd104aced2a14b1050686e490954704573262)
```suggestion
```

2021-07-06 00:01 UTC, famole commented on src/views/Dashboard/emptyState.tsx
> +  }, [type]);
thanks for the explanation, I wasn't sure about using it here.

2021-07-06 00:03 UTC, zedkai approved these changes
Applied the change myself.

2021-07-06 00:03 UTC, merged