fix the APR and APY views and bundled both cases into the same file
Agave-DAO/agave-frontend pull request #45
Opened 2021-07-15 11:55 UTC by Luigy-Lemon

fixed the APR and APY views and bundled both cases into the same file RatesView.tsx - There's room to use a constants file to determine the amount of decimals to display depending on the network, asset, or device being used.

2021-07-15 20:55 UTC, zedkai requested changes
Wait for me before merging this one after fixing things.

2021-07-15 20:55 UTC, zedkai commented on src/utils/fixedPoint.ts
> +  min: number | number = 0
Use a more descriptive parameter name- this is about numbers and you wrote `min`, so it's somewhat ambiguous.

2021-07-15 20:55 UTC, zedkai commented on src/utils/fixedPoint.ts
> +  min: number | number = 0
This isn't how unions work. Read the `|` like the word "OR". You're currently saying you'll accept "a number OR a number".

2021-07-15 20:55 UTC, zedkai commented on src/utils/fixedPoint.ts
> +  while (decimals >= 0 && decimals - min > 0) {
```suggestion
  while (decimals >= min) {
```

2021-07-15 20:55 UTC, zedkai commented on src/views/Dashboard/table.tsx
> +		  <DepositAPYView tokenAddress={value}
Run the Formatter.

2021-07-15 20:55 UTC, zedkai commented on src/views/common/RatesView.tsx
> +      <PercentageView ratio={fixedNumberToPercentage(variableDepositAPY, 7, 2)} />
Why does deposit APY get more decimals than Borrow APY?

2021-07-16 23:16 UTC, Luigy-Lemon commented on src/views/common/RatesView.tsx
> +      <PercentageView ratio={fixedNumberToPercentage(variableDepositAPY, 7, 2)} />
Just because currently the liquidity rates are very low... in the future we probably want to just use an file with constants to handle these values.

2021-07-18 00:43 UTC, zedkai requested changes

2021-07-18 00:43 UTC, zedkai commented on src/utils/fixedPoint.ts
> +  minimumNumberOfDecimals: number | 0
That's also wrong. Now you're saying it must be either a `number` or `2`, which means that it's ... A `number`.
```suggestion
  decimalsTarget: number = 2,
  minimumNumberOfDecimals: number = 0
```
Also consider namings `targetDecimals` and `minDecimalCount`.

2021-07-18 00:43 UTC, zedkai commented on src/views/Dashboard/table.tsx
> +          <Box
The cell renderer should probably be a (private to this file) component if it's got this much content. Up to you.

2021-07-18 00:43 UTC, zedkai commented on src/views/common/PercentageView.tsx
> +  ratio: string;
Why is ratio a string? It's either `FixedNumber`, a `number`, or a `BigNumber`, right?
The whole role of `PercentageView` was to take a numeric input of a numeric ratio and turn it into a human readable output with a sensible amount of decimals.

2021-07-18 00:43 UTC, zedkai commented on src/views/common/RatesView.tsx
> +    return <PercentageView ratio={fixedNumberToPercentage(borrowRate, 4, 2)} />;
Changing numerics to percentages should be done *by* the `PercentageView`, not as a parameter to it.

2021-07-19 13:27 UTC, Luigy-Lemon commented on src/views/common/PercentageView.tsx
> +  ratio: string;
I didn't make this percentageView component it felt completely useless when we have the formatting function to me, but i kept it because i thought someone could still want to use it. 
I will just not use it instead.

2021-07-19 20:38 UTC, zedkai commented on src/views/common/RatesView.tsx
> +  console.log(reserveProtocolData, variableDepositAPY, tokenAddress);
Logging on render is expensive/slow- let's not do that.
```suggestion
```

2021-07-19 20:38 UTC, zedkai approved these changes

2021-07-19 21:53 UTC, zedkai commented on src/views/common/PercentageView.tsx
> +  ratio: string;
Yeah, file it as a bug. It must have slipped past one of my prior reviews.

2021-07-19 21:54 UTC, zedkai approved these changes

2021-07-19 23:40 UTC, merged