fix overflow and dashboard stacking in smaller screen - css fixes
Agave-DAO/agave-frontend pull request #46
Opened 2021-07-16 16:32 UTC by Luigy-Lemon

2021-07-17 18:41 UTC, Luigy-Lemon commented on src/views/Dashboard/table.tsx
> +                <Text fontWeight="bold">{"user"}</Text>
this was mistakenly edited

2021-07-17 18:43 UTC, Luigy-Lemon commented on src/utils/htmlTable.tsx
> +  hidden?: boolean;
This functionality of hiding the collateral column in the Borrow table in the dashboard is not implemented fully and the fact we are using react tables makes it trickier to implement.

2021-07-18 00:34 UTC, zedkai commented on src/utils/htmlTable.tsx
> +  hidden?: boolean;
Hiding columns isn't too hard- you can alter the column spec passed into the display side of the table.

2021-07-18 00:36 UTC, zedkai requested changes

2021-07-18 00:36 UTC, zedkai commented on src/utils/htmlTable.tsx
> +                <Th {...column.getHeaderProps(column.getSortByToggleProps())} {...headStyle}  hidden={hidden}>
Instead of passing `hidden` in- just don't include the column in the render spec passed to the table.

2021-07-18 00:36 UTC, zedkai commented on src/views/Dashboard/table.tsx
> +                <Text fontWeight="bold">{"user"}</Text>
Then undo editing it?

2021-07-18 04:15 UTC, zedkai approved these changes

2021-07-18 04:15 UTC, merged