Fix borrow dash
Agave-DAO/agave-frontend pull request #53
Opened 2021-07-27 13:02 UTC by Luigy-Lemon

Collateral Composition component that is working! Also fixed some formatting on some pages and got rid of the != errors in some views

2021-07-27 19:33 UTC, befitsandpiper approved these changes
nit: consoles

2021-07-27 19:33 UTC, befitsandpiper commented on src/components/Chart/CollateralComposition.tsx
> +  console.log(allUserReservesBalances);
remove console

2021-07-27 19:33 UTC, befitsandpiper commented on src/views/Dashboard/table.tsx
> +    console.log(tokenAddress, reserveUsedAsCollateral);
probably remove console (although maybe this is to help remember we have to do an actual mutation here?)

2021-07-27 22:37 UTC, zedkai requested changes

2021-07-27 22:37 UTC, zedkai commented on src/views/common/BorrowDash.tsx
> +  );
What are you *doing* here? This looks like a possible mash-up of a `React.useMemo` invocation and a Map call, because that `[String]` certainly isn't being used as the `thisArg` in an arrow function.

2021-07-27 22:37 UTC, zedkai commented on src/views/common/BorrowDash.tsx
> +    if (x !== null) return x.substr(0, x.indexOf(".") + 3);
I wonder if this'll cause problems if we have a value of `x` that has no `"."`... I suspect it'll just take the first 3 characters of the string, or complain that you can't add `3` to `undefined`.

Are there any circumstances where `x` *won't* have a `"."` in it? If not, this is fine.

2021-07-27 22:37 UTC, zedkai commented on src/views/common/BorrowDash.tsx
> +          ></CollateralComposition>
If `CollateralComposition` needs these exact input types every time it is used, then it should not take them as props unless they're expected to change contextually.

You should define hooks that produce `allUserReservesData`, `totalCollateralValue`, and `allUserReservesBalances` (or a single hook that produces all 3), and use those *inside of* the `CollateralComposition` component.

2021-07-27 22:37 UTC, zedkai commented on src/views/common/RepayDash.tsx
> +  );
Again with the mysterious `thisArg`?

2021-07-27 23:14 UTC, Luigy-Lemon commented on src/views/common/BorrowDash.tsx
> +    if (x !== null) return x.substr(0, x.indexOf(".") + 3);
yeah you are right. But this is always coming from BigNumbers so it should always have a "." since in the case of 0 i filter that out from the array

2021-07-27 23:42 UTC, Luigy-Lemon commented on src/views/common/BorrowDash.tsx
> +          ></CollateralComposition>
Yeah mid-way through i was thinking the same. i was sort of avoiding making more duplicate queries in nested views. I will fix that up.

2021-07-27 23:53 UTC, zedkai requested changes
Almost there- still need to make this behaviour into shareable functions or - if necessary - hooks.

2021-07-27 23:53 UTC, zedkai commented on src/components/Chart/CollateralComposition.tsx
>    const collateralComposition = React.useMemo(() => {
Split computation of `collateralComposition` into a hook named `useCollateralComposition`.

2021-07-27 23:53 UTC, zedkai commented on src/views/common/RepayDash.tsx
> +        <CollateralComposition></CollateralComposition>
```suggestion
        <CollateralComposition/>
```

2021-07-27 23:53 UTC, zedkai commented on src/views/common/BorrowDash.tsx
> +          <CollateralComposition></CollateralComposition>
```suggestion
          <CollateralComposition/>
```

2021-07-27 23:54 UTC, zedkai commented on src/views/common/BorrowDash.tsx
> +    if (x !== null) return x.substr(0, x.indexOf(".") + 3);
`BigNumber` doesn't have a `"."` ever, but I suspect you know what you mean here, so I'll allow this as a close reason- just keep an eye out for "Why do we only have 3 digits shown on a larger number?" or "Why are we getting an `undefined` addition error?" scenarios.

2021-07-30 23:51 UTC, zedkai requested changes

2021-07-30 23:51 UTC, zedkai commented on src/hooks/collateralComposition.ts
> +    : [];
This section needs `React.useMemo`, or the array creations will trigger a rerender of all child types every time. I would suggest making a function that takes the inputs used by these lines, then using *it* inside the `React.useMemo` call.

2021-07-31 02:11 UTC, Luigy-Lemon commented on src/hooks/collateralComposition.ts
> +    : [];
Will see if i can figure out what you mean.

2021-08-01 00:13 UTC, zedkai approved these changes

2021-08-01 06:23 UTC, merged