Fix my deposits
Agave-DAO/agave-frontend pull request #54
Opened 2021-07-27 14:35 UTC by Luigy-Lemon

Similar change to My Deposits that has been already pushed for My Borrows

2021-07-27 19:21 UTC, befitsandpiper approved these changes
nit: please remove console log then you can merge the PR.

2021-07-27 19:21 UTC, befitsandpiper commented on src/views/Borrow/index.tsx
> +  console.log(balances);
remove console

2021-07-27 22:53 UTC, zedkai requested changes
Unnecessary code duplication.

2021-07-27 22:53 UTC, zedkai commented on src/views/Borrow/MyBorrows.tsx
>              </Text>
Looks like this construct is repeated twice in this PR and at least once in https://github.com/Agave-DAO/agave-frontend/pull/52/files#diff-6d276eb2737964ef22c916f27e5c3f46e79f6ce2dba7d4ce39ddc5e01e16ff15R28-R41

As this is a derived commit from the PR #52, please revise *this* PR such that it turns that block from 52 into its own component that takes (`balance`, `daiWeiPricePer`, and `daiWeiPriceTotal`) *or* (`asset`) as parameters, put it in [`components`](https://github.com/Agave-DAO/agave-frontend/tree/dev/src/components), and use it in these two places to share the formatting and behaviours exactly.

2021-07-27 22:53 UTC, zedkai commented on src/views/Deposit/MyDeposits.tsx
> +              $ {bigNumberToString(asset.daiWeiPriceTotal)}
Use the component created in response to my other comment.

2021-07-28 01:59 UTC, zedkai approved these changes
Nice deduplication.

2021-07-28 02:03 UTC, zedkai requested changes
Missed this one since it was from a prior PR.

2021-07-28 02:03 UTC, zedkai commented on src/views/Deposit/MyDeposits.tsx
>        0
Wait a minute- why are you using Number here? This should stay BigNumber until it becomes display-output-truncated.
If you're turning it into a display-value, do so *after* adding everything.

`reduce((memo, next) => next.daiWeiPriceTotal !== undefined ? memo.add(next.daiWeiPriceTotal) : memo, constants.Zero)`

2021-07-30 23:53 UTC, zedkai approved these changes

2021-07-31 02:10 UTC, merged