navbar overhaul
Agave-DAO/agave-frontend pull request #56
Opened 2021-07-29 17:16 UTC by Affinity-Design

Navbar Desktop & Mobile Overhaul | July 29th, 2021

✔ Desktop navbar clean up, CSS improvements
✔ Connect Button Working
✔ Dark Light Button Working
✔ Agave Amt Button Working 
✔ Mobile Navbar implement 
✔ Mobile Dropdown Menu Overhaul 

Navbar Refactor | Aguest 3rd, 2021
✔ Replaced child-type introspection with separated components 
✔ Replaced dubious code with refactored components 
✔ Fixed JS stateful sizing with flexbox fraction CSS sizing

2021-07-31 00:09 UTC, zedkai requested changes
This is a very nice feature-set, but the implementation is dubious and has some aspects that make it rather difficult to maintain or reason about.

2021-07-31 00:09 UTC, zedkai commented on src/components/Header/index.tsx
> +  };
Don't do this here at all. This is already taken care of [in the Index](https://github.com/Agave-DAO/agave-frontend/blob/f24404cdd01b6d7729555474af8d5c3b124cda7a/src/index.tsx#L30) where we call [useAmbientConnection](https://github.com/Agave-DAO/agave-frontend/blob/f24404cdd01b6d7729555474af8d5c3b124cda7a/src/hooks/injectedConnectors.ts#L10) to accomplish this more gracefully.

2021-07-31 00:09 UTC, zedkai commented on src/components/Header/mobile-nav.tsx
> +            // TODO top={{ base: "80px", md: "50px" }}
What's left to do here? A comment explaining the nature of the TODO should always be present alongside it, in case someone else wants to fix it.

2021-07-31 00:09 UTC, zedkai commented on src/components/Header/navbar.tsx
> +  }, [boxWidth]);
JS-based stateful sizing... Is there any way to avoid this using CSS?

2021-07-31 00:09 UTC, zedkai commented on src/components/Header/navbar.tsx
> +              </Flex>
Please don't use child-type introspection to handle rendering.

2021-07-31 00:09 UTC, zedkai commented on src/components/Header/navbar.tsx
> +    <React.Fragment>
This component's output is enormous and filled with a million lines of CSS-esque properties; can you break parts of it down into separate components (even unexported, single-use ones)? This rerenders the entire navbar with basically any interaction, as it currently stands.

2021-07-31 00:09 UTC, zedkai commented on src/components/Header/navbar.tsx
> +                  .children
More child-type introspection.

2021-08-04 02:05 UTC, zedkai requested changes

2021-08-04 02:05 UTC, zedkai commented on src/components/Header/NavComponents/BGimage.tsx
> +interface Props {
Generally, if you're going to name the `Props` type for a component, you should name it something like `<Component>Props`, in this case `AgveBGProps`.

Incidentally, try not to abbreviate things unnecessarily; `AgaveBackground` would be preferable over `AgveBG`.

2021-08-04 02:05 UTC, zedkai commented on src/components/Header/NavComponents/BGimage.tsx
> +    <React.Fragment>
Fragments are expensive to render- use them only when you don't have a true single root element; in this case, `Center` should be the root element for the FC.

2021-08-04 02:05 UTC, zedkai commented on src/components/Header/NavComponents/brand.tsx
> +export const Brand: React.FC<any> = props => {
`React.FC<{}>`, not `any`; you explicitly want _no props_ for now, as the props remain unused.

The definition should be handled with `() => {` instead of `props => {` in this case.

2021-08-04 02:05 UTC, zedkai commented on src/components/Header/NavComponents/brand.tsx
> +export const Brand: React.FC<any> = props => {
Do the same for the "Links" component and any others that followed this `any` pattern.

2021-08-04 02:05 UTC, zedkai commented on src/components/Header/NavComponents/links.tsx
> +export const Links: React.FC<any> = props => {
This is very specific (completely unreusable) and probably shouldn't be a publicly exported component, let alone have its own file.

2021-08-04 02:05 UTC, zedkai commented on src/components/Header/mobile-nav.tsx
> +        {mobileNav.isOpen && (
MobileNav is the disclosure content, right? If it's open, the content must necessarily always be open, so:
`<MobileNavContent isOpen={mobileNav.isOpen} ... />` is equivalent to having a property which is always set to true; is there a reason this is not the case here?

2021-08-04 02:05 UTC, zedkai commented on src/components/Header/NavComponents/userprofile.tsx
> +      {addressPretty ? (
`addressPretty` is always truthy; if they are not connected, it literally becomes the string `"Not Connected"` which is truthy in JS. Thus the alternate branch of this ternary is never evaluated.

2021-08-04 02:24 UTC, Affinity-Design commented on src/components/Header/NavComponents/tab-link-style.tsx
> +// export const NavTabLink: React.FC<LinkProps & NavLinkProps<unknown>> = props => {
A previous dev left this is it still valid?

2021-08-04 02:41 UTC, Affinity-Design commented on src/components/Header/NavComponents/links.tsx
> +export const Links: React.FC<any> = props => {
I needed to reference the links component in the mobile-nav and the desktop-nav (index.tsx) component which is two different places, this export avoids duplication of the link items. It may be able to be done with props but I thought this solution was a bit easier to maintain.

2021-08-04 02:55 UTC, Affinity-Design commented on src/components/Header/mobile-nav.tsx
> +        {mobileNav.isOpen && (
I believe the isOpen state defaults to false. So when the first render occurs there is no animation. When the onclick event happens in the mobile-nav-content component (aka the tab menu is clicked) it triggers either the onOpen or onClose event based on whatever the isOpen state is not correctly closing or opening the overlay and triggering the animation.

2021-08-04 06:20 UTC, zedkai commented on src/components/Header/NavComponents/links.tsx
> +export const Links: React.FC<any> = props => {
That's a fair reason; I'm surprised desktop and mobile nav are different components, but I'll consider this resolved.

2021-08-04 07:03 UTC, zedkai requested changes

2021-08-04 07:03 UTC, zedkai commented on src/components/Header/NavComponents/mobile-nav-content.tsx
> +    <React.Fragment>
You still need to fix your redundant fragment layers.

2021-08-04 07:05 UTC, zedkai commented on src/components/Header/mobile-nav.tsx
> +        {mobileNav.isOpen && (
I'm not clear why `isOpen={mobileNav.isOpen}` is present at all if it's predicated on the factor `mobileNav.isOpen` to display it. If you insist this is correct, I'd appreciate either a followup PR or a change to this one isolate this behaviour and disambiguate the duplicate MobileNavContent portions.

2021-08-04 15:21 UTC, Affinity-Design commented on src/components/Header/NavComponents/mobile-nav-content.tsx
> +            onClick={isOpen ? onClose : onOpen}
The mobile overlay behavior is handled inside the mobile-nav-content component. This is why I needed to pass down the state from the parent component  isOpen={mobileNav.isOpen}. It's crucial for the function of the IconButton to handle opening and closing the overlay. I would have handled this state here entirely if I didn't need it on the parent component to handle the animation of the overlay itself. Since I can't pass the state backward, I simply passed it down the component tree.

2021-08-04 16:16 UTC, Affinity-Design commented on src/components/Header/mobile-nav.tsx
> +        {mobileNav.isOpen && (
I answered your _isOpen_ concern in another comment referring to the line it affects. 

As for the clarity for why I used two navbars, here's my rationale. I posted a short video to discord to help demonstrate why i used two MobileNavBar Instances. 

First, I will be renaming the _MobileNavContent_ component to _MobileNavBar_ for more clarity. 

There are two MobileNavBar components being rendered to the screen. The first one exists in the normal document at the very top, if there is excess content on the screen beyond the height of the screen then when I scroll the navBar will shift up, which is the normal expected default behavior. 

When I tap the hamburger icon I wanted the nav-overlay to render overtop whatever content is displayed on the screen. 
In order to achieve that effect, I wanted to negate the entire document flow entirely and create a component that fills the entire height and width of the screen. I can do that with the absolute position property. 

The only downside to this, that now when I open the overlay it creates a bad UX pattern which removes the navbar out of view entirely, At first, I thought let's just shift down the overlay to the same height as the navBar. However, this has a bad limitation that now if accidentally scroll, the navbar shifts out of view. This is because if the document below has the potential to scroll down, the overlay will stay put but the header itself will shift out of view since it's still in the normal document flow below.  

My solution to this was just to create a second instance of the mobileNavBar to exist on the same absolute layer as the overlay. So now, when a user taps the hamburger icon, essentially an entirely new menu appears over the document below. To a user, it looks identical and behaves as expected but in reality, its placed right over top of the existing document and subsequent navbar below but now if a user accidentally scrolls nothing happens since its all locked in place, as soon as a user makes the desired action the overlay vanishes revealing the first mobileNavBar and newly rendered content below which is needed to trigger the overlay and navigation.

2021-08-05 02:58 UTC, zedkai commented on src/components/Header/mobile-nav.tsx
> +        {mobileNav.isOpen && (
Acceptable, though a fixed bar at the top may be more manageable for future implementations.

Resolved.

2021-08-05 03:00 UTC, zedkai approved these changes
Approved pending solution of the Fragment wrappers. Merge *after* they're removed.

2021-08-06 01:01 UTC, zedkai requested changes
You just re-added react fragments. `<> </>` is shorthand for `<React.Fragment> </React.Fragment>`. Read the text.

2021-08-06 01:37 UTC, merged