Feature health factor calculator
Agave-DAO/agave-frontend pull request #57
Opened 2021-07-31 02:08 UTC by Luigy-Lemon

2021-07-31 02:20 UTC, zedkai requested changes

2021-07-31 02:20 UTC, zedkai commented on src/utils/propertyCalculator.ts
> +  const memoTokenAddress = React.useMemo(() => tokenAddress, [tokenAddress]);
This is absolutely pointless; don't memoize inputs- make functions when you don't need a hook.

2021-07-31 02:20 UTC, zedkai commented on src/utils/propertyCalculator.ts
> +      : undefined;
This whole block is computation, not rendering. Make it a separate function- not a hook or a component- just a function.

2021-07-31 02:20 UTC, zedkai commented on src/utils/propertyCalculator.ts
> +  return newHealthFactor;
Same comments I mentioned for CollateralChange.
Additionally, see if any aspects of the function you create for computation can be shared between the calculations you do in the second comment.

2021-07-31 02:21 UTC, zedkai commented on src/utils/propertyCalculator.ts
> +      : undefined;
Also, memoize the results of that function based on its inputs, when calling it in this hook.

2021-08-01 00:20 UTC, zedkai approved these changes
A few comments for changes I'd like to see in future PRs.

2021-08-01 00:20 UTC, zedkai commented on src/utils/propertyCalculator.ts
> +  increase?: Boolean | false
`Boolean` is equivalent to `true | false`, so you have `true | false | false`, which reduces to `true | false`.

2021-08-01 00:20 UTC, zedkai commented on src/utils/propertyCalculator.ts
> +      ? amount.mul(tokenData.assetPrice).div(weiPerToken(18))
I'm slightly concerned that we have this hardcoded 18-digit state here; How hard would it be to include decimal information in the future to ensure we get the correct digit counts across all tokens?

(Note: I am not holding this PR back on this request- I *would* like to see it done in a future PR though)

2021-08-01 02:42 UTC, Luigy-Lemon commented on src/utils/propertyCalculator.ts
> +      ? amount.mul(tokenData.assetPrice).div(weiPerToken(18))
Actually in this case we want to force the 18 because the assetPrice is in daiWei so it's always 18 decimals even for the tokens with less decimals

2021-08-01 02:43 UTC, merged